baseurl: "/dizer-jekyll" # the subpath of your site, e.g. /blog
url: "https://demo.themefisher.com" # the base hostname & protocol for your site, e.g. http://example.com or  https://Dizerjk.netlify.com
title: "Dizer -  Multipurpose Business & Corporate Jekyll Template"
email: "themefisher@gmail.com"
phone: "+21 123 456 5523"
address: "9567 Turner Trace Apt. 466 North Willie, BC C3G8A4"
author: themefisher
description: >- # this means to ignore newlines
  Dizer - Multipurpose Business & Corporate Jekyll Template Jekyll Theme For Mobile Apps Download Landing Page And Blogging.
logo: "/assets/images/logo.png"
logo_icon: "/assets/images/logo-b.png"
# contact form action
contact_form_action: "#" # works with https://fomrspree.io
mailchimp_list: "https://themeix.us16.list-manage.com/subscribe/post?u=307862c135e4548eecf86f389&amp;id=342411fb35"
footer_content: "Lorem ipsum dolor amet consectetur adipielit sed eiusm tempor incididunt ut labore dolore magna aliqua enim ad minim veniam."
copyright: "dizer. &copy; 2020 All Right Reserved"
# page header default image
cover_image: "/assets/images/bg/about-bg.jpg"
google_map_api: "https://maps.googleapis.com/maps/api/js?key=AIzaSyDnh74UN6BKgq9U5fMNGhdZOSpmM_QnZqs"

############### Call to Action ###############
cta:
  enable: true
  title: "dizer give the smart solution for your business"
  bg_image: "/assets/images/bg/cta-bg-2.png"
  button:
    label: "get a quote"
    link: "contact"

################## Social site ###############
social:
  - name: facebook
    icon: "ti-facebook"
    link: "#"

  - name: twitter
    icon: "ti-twitter-alt"
    link: "#"

  - name: linkedin
    icon: "ti-linkedin"
    link: "#"

  - name: pinterest
    icon: "ti-pinterest"
    link: "#"

# Build settings
permalink: "/:title"
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-archives

# Scss Directory
sass:
  sass_dir: assets/scss
  style: compressed

#collections
collections:
  portfolios:
    output: true

########################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:
  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination page
  debug: true

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: "posts"

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 6

  # The permalink structure for the paginated pages (this can be any level deep)
  #permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  permalink: "/blog/:num/" # Pages are simple html file
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ":title - page :num"

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0

  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: "date"

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: "posts"

  # Optional, the default tag to use, omit to disable
  tag: ""

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts,
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: ""

  # Optional,omit or set both before and after to zero to disable.
  # Controls how the pagination trail for the paginated pages look like.
  trail:
    before: 2
    after: 2

  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: "html"

  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: "index"

tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

jekyll-archives:
  enabled: all
  layout: category
  permalinks:
    category: "/category/:name/"

feed:
  collections:
    posts:
      path: "/index.xml"
